[target.thumbv7em-none-eabi]
# Search this docker image with this name, and compile on that
# You can list docker images with command "docker images"
image = "teensy3/cross:tag"

[target.thumbv7em-none-eabihf]
image = "teensy3/cross:tag"
